package phenotogeno.validation;

import io.FileOutputWriter;

public abstract class PatientSimulatorWriteToFile implements PatientSimulator {
	
	/** counter for generating the id of the current patient*/
	private int currentId;
	/** writer for file of all generated patients */
	private FileOutputWriter patientWriter;
	
	/** 
	 * generates a PatientSimulator that simulates patients and writes them to a file
	 * @param path path to the file to which the patients are written
	 */
	public PatientSimulatorWriteToFile(String path) {
		currentId = 0;
		patientWriter = new FileOutputWriter(path);
	}
	
	/** ends the simulation by closing the writer for the patient file*/
	public void endSimulation(){
		patientWriter.closew();
	}
	
	/**
	 * retrieves the current patient id for generating a new patient with that id
	 * @return the current patient id
	 */
	protected int getCurrentId(){
		return currentId;
	}
	
	/**
	 * writes the current patient to the file with all patients and increases the currentId by one
	 * @param patient Simulated patient generated by this simulator
	 */
	protected void writePatient(SimulatedPatient patient){
		currentId++;
		patientWriter.writeFileln(patient.toString());
	}

}
