package phenomizer.algorithm;

import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedList;

import io.FileInputReader;

public class PhenomizerAlgorithmWithPval extends PhenomizerAlgorithm {
	
	private PValueFolder folder;
	private PValueCorrector corrector;
	
	/**
	 * creates a PhenomizerAlgorithmWithPval object
	 * runs the PhenomizerAlgorithm and calculates pvalues from pre-determined score distributions
	 * @param num: number of diseases in the output of Phenomizer
	 * @param ontology: Ontology object representing is-a relationship between PhenoDis symptoms
	 * @param queryIds: contains PhenoDis ids of the query symptoms
	 * @param sda: associations between diseases and symptoms annotated in PhenoDis
	 * @param similarityCalculator: calculates the similarity score between a query and a disease
	 * @param folder: PValueFolder object for managing access to the pre-determined score distributions
	 * @param corrector: PValue corrector object
	 */
	public PhenomizerAlgorithmWithPval(int num, Ontology ontology, LinkedList<Integer> queryIds,
			SymptomDiseaseAssociations sda, SimilarityCalculator similarityCalculator, PValueFolder folder,
			PValueCorrector corrector) {
		
		super(num, ontology, queryIds, sda, similarityCalculator);
		this.folder=folder;
		this.corrector = corrector;
		this.comparator = new ComparatorPhenoPval();
	}

	@Override
	/**
	 * executes the Phenomizer algorithm
	 * @return: prediction results of Phenomizer for the current query
	 * 		the results are stored in a linked list of String arrays
	 * 		each list entry is an array corresponding to a disease
	 * 		array elements: array[0] disease id, array[1] similariy score, array[2] pvalue
	 */
	public LinkedList<String[]> runPhenomizer() {
		
		//calculate IC
		setIC();
		//get similarity scores for all diseases
		HashMap<Integer,Double> resPhenomizer = scoreQuery();
		
		//calculate and correct pvalues + keep sorting order
		String pvalue_file = folder.getPvalFile(queryIds.size());
		String[][] array_result = getPvalues(resPhenomizer, pvalue_file);
		correctPvalues(array_result);
		
		//generate output data structure with defined number of entries
		return generateResult(array_result);
	}
	
	/**
	 * calculates the similariy between the query and all diseases in PhenoDis
	 * the similarity scores are rounded to 3 decimal places and stored in a HashMap
	 * @return HashMap with mapping PhenoDis disease id-> similarity score of the disease and the query
	 */
	private HashMap<Integer,Double> scoreQuery(){
		
		HashMap<Integer,Double> result = new HashMap<Integer,Double>(sda.numberOfDiseases()*3);
		for(int disease : sda.getDiseases()){
			double similarity = similarityCalculator.calculateSymmetricSimilarity(queryIds,sda.getSymptoms(disease));
			//round score to 3 decimal places
			similarity = (double) Math.round(similarity*1000)/1000;
			result.put(disease,similarity);
		}
		
		return result;
	}
	
	/**
	 * calculates the pvalues for similarity scores according to pre-determined score distributions
	 * @param scores: Hashmap that maps a disease id to a similarity score
	 * @param path: path to the file containing the score distribution for the appropriate query size
	 * 	the file is generated by a ScoreDistributionSampling object
	 * @return: 2d array with pvalues
	 * 	each row corresponds to a disease in PhenoDis
	 * 	columns: array[][0] disease id, array[][1] similariy score, array[][2] pvalue
	 */
	private String[][] getPvalues(HashMap<Integer,Double> scores, String path){
		
		//phenoResult[][0]: disease id	phenoResult[][1]: score	phenoResult[][3]: pvalue
		String[][] phenoResult = new String[scores.size()][3];
		
		//read line-wise score distribution file, each line contains the distribution for one disease
		FileInputReader fir = new FileInputReader(path);
		String line ="";
		int pos=0;
		
		while((line=fir.read())!=null){
			String [] counts = line.split("\t");
			
			//get disease id: 1st column
			String disease_id = counts[0];
			
			//get score for disease
			double disease_score = scores.get(Integer.valueOf(disease_id));
			
			//calculate pvalue
			int index = (int) Math.round(disease_score*1000)+1;
			int score_count=0;
			if(index<counts.length){
				score_count=Integer.valueOf(counts[index]);
			}
			int total_count = Integer.valueOf(counts[1]);
			double disease_pval = (double) score_count/ total_count;
			
			//save results in String array phenoResult
			phenoResult[pos][0]=disease_id;
			phenoResult[pos][1]=String.valueOf(disease_score);
			phenoResult[pos][2]=String.valueOf(disease_pval);
			pos++;
		}
		
		fir.closer();
		
		//sort result according to pvalue, score and disease id
		Arrays.sort(phenoResult, comparator);
		
		return phenoResult;
	}
	
	/**
	 * corrects the pvalues stored in column 2 of the 2d array results, the old pvalues are overwritten
	 * @param results: 2d array 
	 * 	each row corresponds to a disease in PhenoDis
	 * 	columns: array[][0] disease id, array[][1] similariy score, array[][2] pvalue
	 */
	private void correctPvalues (String [][] results){
		
		//copy pvalues from results into new array
		double [] pvals = new double[results.length];
		//current position in pvals array
		int pos=0;
		//iterate over all diseases in result
		for(String[] r : results){
			pvals[pos]=Double.valueOf(r[2]);
			pos++;
		}
		
		//correct pvalues
		double [] corrected_pvals = corrector.correctPVals(pvals,sda.numberOfDiseases());
		
		//replace pvalues in results with the corrected pvalues to the result
		pos=0;
		for(String[] r : results){
			r[2]=String.valueOf(corrected_pvals[pos]);
			pos++;
		}
		
		Arrays.sort(results, comparator);
	}
	
}
